/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import OCR.OCROnTiFImage;
import static com.lizardtech.djview.frame.StatusBar.ConvertStatus;
import static com.lizardtech.djview.frame.StatusBar.ConvertStatus2;
import java.awt.FileDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Hussein Mohamed
 */
public class ChoosePanel extends javax.swing.JPanel {

    /**
     * Creates new form ChoosePanel
     */
    public ChoosePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Choose Image Language:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Arabic", "Franch" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, 20));
    }// </editor-fold>//GEN-END:initComponents
 public static String Title = null;
    OCROnTiFImage ocr = new OCROnTiFImage();
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
           // frame.add(ChoosePanel);

        try {
            FileDialog imageocr = new FileDialog(new java.awt.Frame(), "Select Images", FileDialog.LOAD);
            imageocr.setVisible(true);
            String imagepath = imageocr.getDirectory() + imageocr.getFile();
            String d = null;
            if (imagepath != null) {
                d = imagepath.substring(imagepath.lastIndexOf("."));
                d = d.toLowerCase();
                OCROnImagePanel.frame.dispose();
                if (d.equals(".jpg") | d.equals(".jpeg") | d.equals(".tif") | d.equals(".png")) {
                    if (jComboBox1.getSelectedItem().toString().equals("English")) {
                        System.err.println("mmmmeeeeeeeeeeemmmmmmmmm");
                        // OCROnImagePanel.Ocrst.setVisible(true);
                        Title = "English";
                        ocr.OCRForImage(imagepath, "en");

                        OCROnImagePanel.Ocrst.setVisible(false);
                        ConvertStatus.setVisible(false);
                        ConvertStatus2.setVisible(false);

                    } else if (jComboBox1.getSelectedItem().toString().equals("Arabic")) {
                        System.err.println("mmmmmmmmmmmmm");
                        // OCROnImagePanel.Ocrst.setVisible(true);
                        Title = "Arabic";
                        ocr.OCRForImage(imagepath, "ara");
                        OCROnImagePanel.Ocrst.setVisible(false);
                        ConvertStatus.setVisible(false);
                        ConvertStatus2.setVisible(false);

                    }

                } else {
                    OCROnImagePanel.Ocrst.setVisible(false);
                    ConvertStatus.setVisible(false);
                    ConvertStatus2.setVisible(false);
                    OCROnImagePanel.frame.dispose();
                    JOptionPane.showMessageDialog(null, "File is selected is not image\nPlease select image");
                    OCROnImagePanel.frame.dispose();
                }
            } else {
                OCROnImagePanel.Ocrst.setVisible(false);
                ConvertStatus.setVisible(false);
                ConvertStatus2.setVisible(false);
                OCROnImagePanel.frame.dispose();
                JOptionPane.showMessageDialog(null, "Please select image");
                OCROnImagePanel.frame.dispose();
            }
        } catch (Exception er) {

        } finally {
            OCROnImagePanel.Ocrst.setVisible(false);
            OCROnImagePanel.frame.dispose();
            ConvertStatus.setVisible(false);
            ConvertStatus2.setVisible(false);

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
