/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MainPage;

import PDF2DjVu.DjVU2TIF;
import static PDFIMG.PDF2IMG.convertToIMG;
import java.awt.FileDialog;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Hussein Mohamed
 */
public class Djvu2Images extends javax.swing.JPanel {

    /**
     * Creates new form Djvu2Images
     */
    FileDialog djvuFileSelectDialog=null;
    String djvuSelectFullPath=null;
    String newPDFFullPath=null;
    public Djvu2Images() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DjVuPDF2 = new javax.swing.JButton();
        jLabell2 = new javax.swing.JLabel();
        Djvust = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabell3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(390, 140));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DjVuPDF2.setBackground(new java.awt.Color(102, 0, 204));
        DjVuPDF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DJVU toImg48.png"))); // NOI18N
        DjVuPDF2.setToolTipText("Select Your DjVu");
        DjVuPDF2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DjVuPDF2.setOpaque(false);
        DjVuPDF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DjVuPDF2ActionPerformed(evt);
            }
        });
        add(DjVuPDF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 48));

        jLabell2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell2.setForeground(new java.awt.Color(0, 0, 102));
        jLabell2.setText("Select Your DjVu");
        add(jLabell2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Djvust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BAR.gif"))); // NOI18N
        add(Djvust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 50));
        Djvust.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Convert Djvu Into Images");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabell3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white with blue.png"))); // NOI18N
        add(jLabell3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void DjVuPDF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DjVuPDF2ActionPerformed
        // TODO add your handling code here:
   Djvust.setVisible(true);
            try{
            djvuFileSelectDialog=new FileDialog(new java.awt.Frame(),"Select DjVu",FileDialog.LOAD);
            djvuFileSelectDialog.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/DjvuIcon.png")));
            djvuFileSelectDialog.setVisible(true);
            djvuSelectFullPath=djvuFileSelectDialog.getDirectory()+djvuFileSelectDialog.getFile();
            if(djvuFileSelectDialog.getFile() != null){
                
                    String d=djvuSelectFullPath.substring(djvuSelectFullPath.lastIndexOf("."));
                    d=d.toLowerCase();
                    String djvupath= "\"" + djvuSelectFullPath + "\""; // skip spaces 
                    if (d.equals(".djvu")) {
                           FileDialog SaveDjVu = new FileDialog(new java.awt.Frame(), "Save Images", FileDialog.SAVE);
                           SaveDjVu.setVisible(true);
                           String path = SaveDjVu.getDirectory()+SaveDjVu.getFile();
                        if(path!=null&&SaveDjVu.getFile()!= null){
                            DjVU2TIF.convertDjvu2PDF(djvupath, "C:\\DjVu++Task\\outp", 0);
                            convertToIMG("C:\\DjVu++Task\\outp.pdf",path, 2);
                            }
                        
                    }else {
                        JOptionPane.showMessageDialog(null, "File selected is not Djvu");
                        djvuSelectFullPath = null;
                    }
            
            }
            }catch(Exception ex){}
            finally{
                File write = new File("C:\\DjVu++Task\\tiffff.tif");
                            if (write.exists()) {
                                write.delete();
                            }
               
                Djvust.setVisible(false);
                File tf=new File("C:\\DjVu++Task\\outp.pdf");
                if(tf.exists()){
                    tf.delete();
                    tf.deleteOnExit();
                }
            }

 
    }//GEN-LAST:event_DjVuPDF2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DjVuPDF2;
    private javax.swing.JLabel Djvust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabell2;
    private javax.swing.JLabel jLabell3;
    // End of variables declaration//GEN-END:variables
}
