/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import PDF2DjVu.PDF2DjVu;
import PDFIMG.IMAGEStoPDF;
import com.lizardtech.djview.frame.DjvuStart;
import static com.lizardtech.djview.frame.DjvuStart.curropen;
import static com.lizardtech.djview.frame.DjvuStart.name_url;
import static com.lizardtech.djview.frame.DjvuStart.tabbedPane;
import static com.lizardtech.djview.frame.DjvuStart.url_name;
import java.awt.FileDialog;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author salah Ben Atwa
 */
public class Images2DjVuPanel extends javax.swing.JPanel {

    /**
     * Creates new form Images2DjVuPanel
     */
    String imdjvu;
    String openimgs = "";
    String PDFFullsource = null;
    File imagess[];
    String[] imageNAME;

    public Images2DjVuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wweq = new javax.swing.JLabel();
        images2djVu = new javax.swing.JButton();
        Djvust = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wweq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wweq.setForeground(new java.awt.Color(0, 0, 102));
        wweq.setText("Select Your Images");
        add(wweq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        images2djVu.setBackground(new java.awt.Color(204, 51, 0));
        images2djVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgs toDJVU 48.png"))); // NOI18N
        images2djVu.setToolTipText("Select Multiple image File");
        images2djVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        images2djVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                images2djVuActionPerformed(evt);
            }
        });
        add(images2djVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 50));

        Djvust.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Djvust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BAR.gif"))); // NOI18N
        add(Djvust, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 10));
        Djvust.setVisible(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Convert Images Into Djvu");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white with blue.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void images2djVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_images2djVuActionPerformed
        // TODO add your handling code here:

        Djvust.setVisible(true);

        FileDialog imagestoconvert2djvu = new FileDialog(new java.awt.Frame(), "Select Images", FileDialog.LOAD);
        imagestoconvert2djvu.setMultipleMode(true);
                imagestoconvert2djvu.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/DjvuIcon.png")));

        imagestoconvert2djvu.setVisible(true);
        String t = imagestoconvert2djvu.getDirectory();
        openimgs = imagestoconvert2djvu.getDirectory() + "\\%s";
        boolean ch = true;
        try {
            if (t != null) {
                imagess = imagestoconvert2djvu.getFiles();
                imageNAME = new String[imagess.length];
                for (int i = 0; i < imagess.length; i++) {
                    imageNAME[i] = imagess[i].getName();
                    String sn = imageNAME[i].substring(imageNAME[i].lastIndexOf("."));
                    sn = sn.toLowerCase();
                    if (sn.equals(".jpg") | sn.equals(".jpeg") | sn.equals(".tif") | sn.equals(".png")) {

                    } else {
                        JOptionPane.showMessageDialog(null, "File selected not image\nPlease select image");
                        t = null;
                        ch = false;
                        break;
                    }

                }
                if (ch) {
                    String path ="C:\\DjVu++Task\\ImgDjVu";
                    IMAGEStoPDF.convertToIMG(imageNAME, "C:\\DjVu++Task\\pdfDjvu.pdf", openimgs, 2);
                    PDF2DjVu.PDF2DjVu("C:\\DjVu++Task\\pdfDjvu.pdf", path, 2);
                    File open = new File(path + ".djvu");
                    String url;
                    url = "" + open.toURI();
                    url = url.substring(5, url.length());
                    String name = open.getName();
                    if (!curropen.contains(name)) {
                        name_url.put(name, url);
                        url_name.put(url, name);
                        curropen.add(name);
                        DjvuStart.unsavedbook.add(url);
                        DjvuStart.openBookInNewTab(url, name);

                    } else if (curropen.contains(name)) {
                        tabbedPane.setSelectedIndex(tabbedPane.indexOfTab(name));
                    } else {
                    }

                }
            }
        } catch (Exception e) {
        } finally {
            Djvust.setVisible(false);

            File tf = new File("C:\\DjVu++Task\\pdfDjvu.pdf");
            if (tf.exists()) {
                tf.delete();
            }
        }


    }//GEN-LAST:event_images2djVuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Djvust;
    private javax.swing.JButton images2djVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel wweq;
    // End of variables declaration//GEN-END:variables
}
