/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import PDFIMG.IMAGEStoPDF;
import java.awt.FileDialog;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author salah Ben Atwa
 */
public class Image2PDFpanel extends javax.swing.JPanel {

    /**
     * Creates new form Image2PDFpanel
     */
    String openimg = null;
    String PDFFullPath = null;
    String[] imagesname;

    public Image2PDFpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel101 = new javax.swing.JLabel();
        Imagesstate = new javax.swing.JLabel();
        pdfstat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(0, 0, 102));
        jLabel101.setText("Select Your Images");
        add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Imagesstate.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Imagesstate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BAR.gif"))); // NOI18N
        add(Imagesstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        Imagesstate.setVisible(false);

        pdfstat.setBackground(new java.awt.Color(204, 51, 0));
        pdfstat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgs toPDF 48.png"))); // NOI18N
        pdfstat.setToolTipText("Select Multiple image File");
        pdfstat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pdfstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfstatActionPerformed(evt);
            }
        });
        add(pdfstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Convert Images Into PDF");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white with blue.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void pdfstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfstatActionPerformed
        // TODO add your handling code here:
        Imagesstate.setVisible(true);

        FileDialog openIMGS = new FileDialog(new java.awt.Frame(), "Select Images", FileDialog.LOAD);
        openIMGS.setMultipleMode(true);
        openIMGS.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/DjvuIcon.png")));
        openIMGS.setVisible(true);
        try {
            openimg = openIMGS.getDirectory() + "\\%s";

            File files[] = openIMGS.getFiles();
            imagesname = new String[files.length];
            boolean ch = true;
            if (openIMGS.getFile() != null) {
                for (int i = 0; i < files.length; i++) {
                    imagesname[i] = files[i].getName();
                    PDFFullPath = "C:\\DjVu++Task\\ImagestoPDF\\" + imagesname[i].substring(0, imagesname[i].lastIndexOf(".")) + ".pdf";
                    String sn = imagesname[i].substring(imagesname[i].lastIndexOf("."));
                    sn = sn.toLowerCase();
                    if (sn.equals(".jpg") | sn.equals(".jpeg") | sn.equals(".tif") | sn.equals(".png")) {

                    } else {
                        JOptionPane.showMessageDialog(null, "File is selected is not image\nPlease select image");
                        openimg = null;
                        ch = false;
                        break;
                    }
                }
                if (ch) {
                    FileDialog SaveDjVu = new FileDialog(new java.awt.Frame(), "Save Pdf", FileDialog.SAVE);
                    SaveDjVu.setVisible(true);
                    String path = SaveDjVu.getDirectory() + SaveDjVu.getFile();
                    if (path != null && SaveDjVu.getFile() != null) {
                        IMAGEStoPDF.convertToIMG(imagesname, path + ".pdf", openimg, 1);
                    }
                }
            } else {
                Imagesstate.setVisible(false);
            }
        } catch (Exception t) {
        } finally {
            Imagesstate.setVisible(false);
        }
    }//GEN-LAST:event_pdfstatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagesstate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pdfstat;
    // End of variables declaration//GEN-END:variables
}
