/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import static com.lizardtech.djview.frame.StatusBar.ConvertStatus;
import static com.lizardtech.djview.frame.StatusBar.ConvertStatus2;
import static com.lizardtech.djvubean.DjVuBean.frame;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author salah Ben Atwa
 */
public class OCROnImagePanel extends javax.swing.JPanel {

    /**
     * Creates new form OCROnImagePanel
     */
    public OCROnImagePanel() {
        initComponents();
        Ocrst.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OCR = new javax.swing.JButton();
        Ocrst = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OCR vs Text 48.png"))); // NOI18N
        OCR.setToolTipText("Select image File (png,jpg,bmp,tif)");
        OCR.setBorder(null);
        OCR.setOpaque(false);
        OCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCRActionPerformed(evt);
            }
        });
        add(OCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 50));

        Ocrst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BAR.gif"))); // NOI18N
        Ocrst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(Ocrst, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));
        Ocrst.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Select Your Image");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Convert text With in image ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white with blue.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));
    }// </editor-fold>//GEN-END:initComponents
public static JFrame frame;
    private void OCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCRActionPerformed
        // TODO add your handling code here:
        Ocrst.setVisible(true);
        frame = new JFrame();
        frame.add(new ChoosePanel());
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setTitle("Choose Your Image Language");
        frame.setSize(340, 80);
        frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/DjvuIcon.png")));
           frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                String ObjButtons[] = {"Yes", "No"};
                int PromptResult = JOptionPane.showOptionDialog(null,
                        "Are you sure to close this window?", "Really Closing?",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                        ObjButtons, ObjButtons[1]);
                if (PromptResult == 0) {
                    ConvertStatus.setVisible(false);
                    ConvertStatus2.setVisible(false);
                    Ocrst.setVisible(false);
                    frame.dispose();
                } else {

                    frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }

        });
    }//GEN-LAST:event_OCRActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OCR;
    public static javax.swing.JLabel Ocrst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
