/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lizardtech.djview.frame;

import AppPackage.AnimationClass;
import static com.lizardtech.djview.frame.DjvuStart.bookList;
import static com.lizardtech.djview.frame.DjvuStart.curropen;
import static com.lizardtech.djview.frame.DjvuStart.name_url;
import static com.lizardtech.djview.frame.DjvuStart.tabbedPane;
import static com.lizardtech.djview.frame.DjvuStart.url_name;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author salah Ben Atwa
 */
public class StartPage extends javax.swing.JFrame {
    
    AnimationClass animation=new AnimationClass();

             
       File file=null;
       FileReader reader=null;
       BufferedReader  bufferedReader=null;
       String filerecent;
       String books[];
       File bookfiless[];
        
       List<String> booksfile = new ArrayList<String>();
       
       int i=0;

    /**
     * Creates new form StartPage
     */
    public StartPage() {
               // read the text ... 
        
        file=new File("RecentBooks.txt");
        try
        {
        reader=new FileReader(file);
        bufferedReader=new BufferedReader(reader);
        while ((filerecent = bufferedReader.readLine()) != null) {
                booksfile.add(i,filerecent);
                i++;
        }
        
        
         int w=0;
        books =new String[i+1];
        bookfiless=new File[i+1];
        for(int a=i;a>=0;a--){
                bookfiless[a]=new File(booksfile.get(w));
                books[a]=bookfiless[a].getName();
                w++;
            }
         
        }catch(Exception ex){}
        
        booklist = new JList(books);
       // booklist.setCellRenderer(new BookCellRenderer());
        booklist.setVisibleRowCount(8);
        
        initComponents();
        
   booklist.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent evt) {

        try
        {
           
         Object sell =null;
        int[] in=booklist.getSelectedIndices();
        sell=booklist.getModel().getElementAt(in[0]);
     
         int index = 0 ;
         for(int i=0;i<books.length;i++){
             if(books[i]==sell){
                 index = i;
                 break;
             }
             }
        
                String url;
                url = "" + bookfiless[index].toURI();
                url = url.substring(5, url.length());
                String name = bookfiless[index].getName();
                 if (!curropen.contains(name)) {
                        name_url.put(name, url);
                        url_name.put(url, name);
                        curropen.add(name);
                        bookList.add(url);
                        DjvuStart.openBookInNewTab(url, name);

                    } else if(curropen.contains(name)) {
                        tabbedPane.setSelectedIndex(tabbedPane.indexOfTab(name));
                    } else { }


        
    }
  
    catch(Exception ex)
    {
    }
    }
   });    
       
    }
    
    
   public JList getrecentfile(){
   
   return booklist;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        DelRecent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        booklist = new javax.swing.JList();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ChangetaskPanel = new javax.swing.JPanel();
        pDF2DjVuPanel1 = new MainPage.PDF2DjVuPanel();
        djVu2PDFPanel1 = new MainPage.DjVu2PDFPanel();
        djvu2Images1 = new MainPage.Djvu2Images();
        image2PDFpanel1 = new MainPage.Image2PDFpanel();
        images2DjVuPanel1 = new MainPage.Images2DjVuPanel();
        oCROnImagePanel1 = new MainPage.OCROnImagePanel();
        pDFToImagePanel1 = new MainPage.PDFToImagePanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1363, 400));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DelRecent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Trash.png"))); // NOI18N
        DelRecent.setToolTipText("Clear all past files You Open");
        DelRecent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DelRecent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelRecentActionPerformed(evt);
            }
        });
        jPanel7.add(DelRecent, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recenetFiles.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 290, 40));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booklist.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return books.length; }
            public Object getElementAt(int i) { return books[i]; }
        });
        booklist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(booklist);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 320));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 290, 350));

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LastPage.png"))); // NOI18N
        jButton1.setToolTipText("Next Task");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FirstPage.png"))); // NOI18N
        jButton2.setToolTipText("Previous Task");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LastPage.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/slectTask.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 60));

        ChangetaskPanel.setLayout(new java.awt.CardLayout());
        ChangetaskPanel.add(pDF2DjVuPanel1, "card2");
        ChangetaskPanel.add(djVu2PDFPanel1, "card3");
        ChangetaskPanel.add(djvu2Images1, "card4");
        ChangetaskPanel.add(image2PDFpanel1, "card5");
        ChangetaskPanel.add(images2DjVuPanel1, "card6");
        ChangetaskPanel.add(oCROnImagePanel1, "card7");
        ChangetaskPanel.add(pDFToImagePanel1, "card8");

        jPanel2.add(ChangetaskPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 140));

        jPanel11.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 430, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tasks.png"))); // NOI18N
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonGo.png"))); // NOI18N
        jButton3.setToolTipText("Go to DJvu++ site");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(false);
        jButton3.setPreferredSize(new java.awt.Dimension(30, 33));
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 50, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OnLine_1.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 230));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TopBanner.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        jPanel11.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 260, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-background.png"))); // NOI18N
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 810, 390));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 810, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1520, 620));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DelRecentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelRecentActionPerformed
        // TODO add your handling code here:
         
//        DefaultListModel listModel = (DefaultListModel) booklist.getModel();
//        listModel.removeAllElements();
//        
        
        File fil=new File("RecentBooks.txt");
        if(!fil.exists())
        {
            System.err.println("kkkkkkkkkk");
        }
        else
        {
        PrintWriter writer=null;
            try {
                writer = new PrintWriter(fil);
                writer.print("");
        
               
            } catch (FileNotFoundException ex) {
                Logger.getLogger(StartPage.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                writer.close();
            }
        }
   
              

    }//GEN-LAST:event_DelRecentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)ChangetaskPanel.getLayout(); 
       cl.next(ChangetaskPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         CardLayout cl = (CardLayout)ChangetaskPanel.getLayout(); 
       cl.previous(ChangetaskPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StartPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangetaskPanel;
    private javax.swing.JButton DelRecent;
    private javax.swing.JList booklist;
    private MainPage.DjVu2PDFPanel djVu2PDFPanel1;
    private MainPage.Djvu2Images djvu2Images1;
    private MainPage.Image2PDFpanel image2PDFpanel1;
    private MainPage.Images2DjVuPanel images2DjVuPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private MainPage.OCROnImagePanel oCROnImagePanel1;
    private MainPage.PDF2DjVuPanel pDF2DjVuPanel1;
    private MainPage.PDFToImagePanel pDFToImagePanel1;
    // End of variables declaration//GEN-END:variables



  
}
