/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MainPage;

import PDF2DjVu.DjVU2PDF;
import static PDFIMG.PDF2IMG.convertToIMG;
import java.awt.FileDialog;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Hussein Mohamed
 */
public class Djvu2Images extends javax.swing.JPanel {

    /**
     * Creates new form Djvu2Images
     */
    FileDialog djvuFileSelectDialog=null;
    String djvuSelectFullPath=null;
    String newPDFFullPath=null;
    public Djvu2Images() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DjVuPDF2 = new javax.swing.JButton();
        jLabell2 = new javax.swing.JLabel();
        Djvust = new javax.swing.JLabel();
        jLabell = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabell3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(390, 140));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DjVuPDF2.setBackground(new java.awt.Color(102, 0, 204));
        DjVuPDF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DJVU 48.png"))); // NOI18N
        DjVuPDF2.setToolTipText("Select Your DjVu");
        DjVuPDF2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DjVuPDF2.setOpaque(false);
        DjVuPDF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DjVuPDF2ActionPerformed(evt);
            }
        });
        add(DjVuPDF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 62, 48));

        jLabell2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell2.setForeground(new java.awt.Color(0, 0, 102));
        jLabell2.setText("Select Your DjVu");
        add(jLabell2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Djvust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pbar.gif"))); // NOI18N
        add(Djvust, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 210, 20));
        Djvust.setVisible(false);

        jLabell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DJVU toImage 48.png"))); // NOI18N
        add(jLabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 62, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Convert Djvu Into Images");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabell3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ttask.png"))); // NOI18N
        add(jLabell3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void DjVuPDF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DjVuPDF2ActionPerformed
        // TODO add your handling code here:
   Djvust.setVisible(true);
            try{
            djvuFileSelectDialog=new FileDialog(new java.awt.Frame(),"Select DjVu",FileDialog.LOAD);
            djvuFileSelectDialog.setVisible(true);
            djvuSelectFullPath=djvuFileSelectDialog.getDirectory()+djvuFileSelectDialog.getFile();
            if(djvuFileSelectDialog.getFile() != null){
                
                    String d=djvuSelectFullPath.substring(djvuSelectFullPath.lastIndexOf("."));
                    d=d.toLowerCase();
                    String djvupath= djvuSelectFullPath; // skip spaces 
                    if (d.equals(".djvu")) {
                           FileDialog SaveDjVu = new FileDialog(new java.awt.Frame(), "Save Images", FileDialog.SAVE);
                           SaveDjVu.setVisible(true);
                           String path = SaveDjVu.getDirectory()+SaveDjVu.getFile();
                        String pdf_path="/home/"+System.getProperty("user.name")+"/.Djvu2Image/output.pdf";
                           if(path!=null&&SaveDjVu.getFile()!= null){
                            
                            DjVU2PDF.convertDjvu2PDF(djvupath,pdf_path, 0);
                            convertToIMG(pdf_path,path, 2);
                            }
                        
                    }else {
                        JOptionPane.showMessageDialog(null, "File selected is not Djvu");
                        djvuSelectFullPath = null;
                    }
            
            }
            }catch(Exception ex){
            }
           finally{
                File write = new File("/home/"+System.getProperty("user.name")+"/.Djvu2Image/output.pdf");
                            if (write.exists()) {
                                write.delete();
                            }
               
                Djvust.setVisible(false);
            }

 
    }//GEN-LAST:event_DjVuPDF2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DjVuPDF2;
    private javax.swing.JLabel Djvust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabell;
    private javax.swing.JLabel jLabell2;
    private javax.swing.JLabel jLabell3;
    // End of variables declaration//GEN-END:variables
}
