/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author salah Ben Atwa
 */
public class OCROnImagePanel extends javax.swing.JPanel {

    /**
     * Creates new form OCROnImagePanel
     */
    public OCROnImagePanel() {
        initComponents();
        Ocrst.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OCR = new javax.swing.JButton();
        Ocrst = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OCRforImage 48.png"))); // NOI18N
        OCR.setToolTipText("Select image File (png,jpg,bmp,tif)");
        OCR.setBorder(null);
        OCR.setOpaque(false);
        OCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCRActionPerformed(evt);
            }
        });
        add(OCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 62, 59));

        Ocrst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pbar.gif"))); // NOI18N
        Ocrst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(Ocrst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, -1));
        Ocrst.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/textselect48_1.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 59));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Select Your Image");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Convert text With in image ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ttask.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 140));
    }// </editor-fold>//GEN-END:initComponents
public static JFrame frame;
    private void OCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCRActionPerformed
        // TODO add your handling code here:
        Ocrst.setVisible(true);
        frame = new JFrame();
        frame.add(new ChoosePanel());
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setTitle("Choose Your Image Language");
        frame.setSize(340, 80);
    }//GEN-LAST:event_OCRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OCR;
    public static javax.swing.JLabel Ocrst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
